version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - ..:/home/app
      - /home/app/node_modules
